### ISSUE TITLE
Add special geometry types

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-geometry#19]
Radiance natively supports geometries like Sphere, Cone and Pipe and [we have them implemented in honeybee already](https://github.com/ladybug-tools/honeybee/tree/3cb8af4faafd6f4bfbb05adb85641396a5133271/honeybee/radiance/geometry). By using these geometrical definitions one can define geometries like tree without adding several 1000s of faces to scene.

Now the question is if we want to add direct support for them in honeybee using ladybug_geometry? It will be useful but I'm not sure how much time it takes to add them and if it does worth the effort.

If we decide to implement the geometries the implementation will be in 3 steps. Let's say we want to add Sphere then we will need.

```
class Sphere(object) -- in ladybug-geometry
```

```
class Sphere(object) -- in honeybee-core
      where self.geometry = ladybug_geometry.Sphere()
```

and finally `honeybee-radiance` adds `Sphere.to.radiance` to Sphere object to generate native radiance Sphere string.

**Comment by chriswmackey** [comment]
Whenever I have seen a geometry interface that has implementations for these types of primitives, I have always said to myself "that's nice" and then almost never used them.  I guess this is because it's exceedingly rare that you want only a perfect sphere but you could use a sphere as a starting point to make a hemisphere for the dome of a building, at which point I'm probably converting the object to a mesh under the hood so that you can perform the intersection.  In other words, we are only using them to save memory in our initial representation and not because we actually want or need them for geometric computation (triangles, quads and polygons are much better for that).

Because of this, I would rather not add them to `ladybug_geometry` because doing so would likely put them outside of the ecosystem of objects that currently talk well with one another in the library.  Or rather, I really don't want to write meshers for all of these objects to make them a part of this ecosystem. If we absolutely need to add them, maybe we can add another folder called `representation3d` that makes it clear they are not really a part of the geometry computation ecosystem and are just there to represent some of the primitives. But, at this point, I would ask why they are in the geometry library, then, if we aren't doing any geometric computation with them?

**Comment by chriswmackey** [comment]
Maybe let me phrase my question another way:

What types of geometric computations do you want to be able to do with these objects that merits having them in the `ladybug_geometry` library as opposed to just representations in `honeybee_radiance`?

If we know that, we can better figure out where they belong.

**Comment by mostaphaRoudsari** [comment]
> What types of geometric computations do you want to be able to do with these objects that merits having them in the ladybug_geometry library as opposed to just representations in honeybee_radiance?

It is not about geometric computations. It is mainly that when they are part of ladybug_geometry then they can be translated to other plugins (e.g. grasshopper) and can be part of the process. We can have workarounds for such use cases. For instance Sphere and Tube and Cone are in particular useful for creating trees in Radiance but I don't think we would ever need to calculate their volume or intersect them.

**Comment by chriswmackey** [comment]
I think this needs more elaboration:
"can be part of the process"

What process are you talking about here?  Do you just want a Grasshopper component that creates a sphere or tree object that is only usable for Radiance simulations and not Energy or any other part of the libraries?  If it's specific Radiance, why doesn't it live in the Radiance library?

What is the list of use-cases where you want to have a generic representation of a sphere object that justifies having it as part of the core geometry library and the geometry translators that we will be writing for every interface of Ladybug Tools? Remember that adding a new geometry object like this can add the extra burden of trying to recognize if a certain CAD object is a sphere or cone as opposed to a generic Brep, which currently only goes to Face3D or Polyface3D.

We don't need to answer this right away. I just think we should have an answer to it if we want to take on the burden of adding another geometry translator for all of the [+] libraries.  All of the objects currently in the `ladybug_geometry` library have several use-cases and the idea behind the [+] libraries is that, just by writing translators for ~15 objects, you can get an entire new plugin for ladybug tools.

So I feel that we should have more of an idea for how we want to use spheres, cylinders and cones before we increase this burden to 18.

**Comment by chriswmackey** [comment]
BTW, I think this is a good issue for anyone who wants to make a contribution to this repo.  Mostapha and talked about this and I didn't realize that the 3 geometry primitives that Radiance uses (Sphere, Cone and Cylinder) are the only ones that exist. So I no longer think that we are over-burdening this repo by adding them but I do think that they should have a lot of the same methods as the other geometry objects.  The sphere is a very good place to start and I would point any contributor to the [euclid.py code for spheres](https://github.com/euclid3/euclid3/blob/master/euclid.py#L2196-L2242) to get started.

**Comment by devgupta2607** [comment]
Hi @chriswmackey @mostaphaRoudsari I am new to this repo and it is difficult to understand the conversation. How can I contribute to this issue ?

**Comment by chriswmackey** [comment]
@devgupta2607 ,

Thinking this over a bit, I am not sure if it's really the best FIRST issue for someone to tackle.  This isn't to say that you couldn't but it's probably going to be a bit more time intensive than other issues we have on our [hacktoberfest board](https://github.com/orgs/ladybug-tools/projects/2). 

If you do want to tackle it, it basically involves creating a new module and class for each of the 3 objects mostapha mentioned (sphere, cylinder and cone).   This involves some thought about the "right way" to implement the minim data needed to describe the object. If you look through this repo, you will see how [the other geometry objects are organized, represented, and what their capabilities are](https://github.com/ladybug-tools/ladybug-geometry/tree/master/ladybug_geometry/geometry3d). I'd pay particularly close attention to the properties they have in common since that means we probably want them to exist on these geometry primitives.

I would recommend starting by adding the sphere and you can borrow some of the code that [euclid uses for sphere geometric calculations here](https://github.com/ezag/pyeuclid/blob/master/euclid.py#L2033-L2114).

**Comment by santiagogaray** [comment]
Hi @chriswmackey 
Is this something that would be helpful to tackle?

**Comment by chriswmackey** [comment]
Yes, @santiagogaray . I think you are well-equipped to tackle this issue since you are already a bit familiar with this repo and you have a good sense of what adding a new class entails. If you want to go for it, I'd recommend putting together just one PR for the sphere and then we can review it and merge it before moving on to cylinder and cone. Just let me know and I'm happy to assign it to you.

**Comment by santiagogaray** [comment]
Sounds good @chriswmackey. I will do a PR with the sphere, with basic functionality to start the conversation.

**Comment by chriswmackey** [comment]
I think we can finally close this issue now that @santiagogaray has sent PRs for all 3 objects.
