### ISSUE TITLE
Add 2D Boolean Union Operations to Polygon2D Class

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-geometry#55]
While we've known for a while that 3D booleans are very complex and we won't really gain much by including them in this library, 2D boolean unions are much more manageable and can be helpful in a number of places throughout Ladybug Tools.  The most obvious application coming to mind right now is the merging of floor plates of a building to yield a footprint (helping manage the translation between 2D representation of buildings and 3D ones).

I can see that someone put together a [small javascript libarary](https://github.com/voidqk/polybooljs) for performing boolean unions and intersections on polygons. If it exists in Javascript, then it should be translate-able to our Python library here. If anyone is willing to take up the mantle of this translation, it would prove very helpful to our workflows.

**Comment by chriswmackey** [comment]
Here is another useful reference for performing this type of calculation:
https://stackoverflow.com/questions/2667748/how-do-i-combine-complex-polygons

I would also note that a method like this would be really useful in THERM workflows to determine the outer boundary segments around the entire model.

**Comment by Derek52** [comment]
I would like to take this issue. If I understand correctly, I am to write a class method in geomtry2d/polygon.py, that takes 2 polygons as input, and returns a new polygon, made by doing the boolean operation?

**Comment by chriswmackey** [comment]
Hi @derek52 ,
That is mostly correct but I think we would prefer it as a staticmethod rather than a classmethod. It can do exactly what you said, though (take 2 polygons and Boolean them into one). If the method could also Boolean adjacent polygons that are within a minimum tolerance distance, that would be ideal but you can start with just booleaning intersecting polygons.
Lastly, I would encourage you to take a look through the [documentation of this repo](https://www.ladybug.tools/ladybug-geometry/docs/ladybug_geometry.html) since there are a lot of capabilities (especially intersections and vectormath) that you can use when crafting this method.

**Comment by Derek52** [comment]
Thanks for the clarification. I'll make a static method. And I will read through the docs, that is a good tip.
I will try and submit a PR in the next day or two.

**Comment by Derek52** [comment]
I'm still working on this issue. I just had a more hectic week than I thought I would. Hopefully I'll solve this sometime this weekend. After beginning to experiment though, I have a couple of questions.

For a boolean union, I've read that if the 2 polygons do not overlap at all, the method should return both separate polygons. How should I handle that case here. Should I return a tuple of the two polygons?

Can you tell me how to test my method? I tried adding a test case to one of the files in the test folder, but because it's a static method, pytest wouldn't run it. I usually only use python for scripts and small little tools, and I'm not too knowledgeable on it's testing frameworks.

**Comment by chriswmackey** [comment]
Hi @Derek52 ,

Sorry for the late response as I was out the last few days.  To answer your questions:

1. I think that it is fine to always return an array from the staticmethod. This way it can be an array of one Polygon if the boolean was successful and an array of two polygons if it was not successful.

2. To test your method, you should just add a function to `polygon2d_test.py` here : https://github.com/ladybug-tools/ladybug-geometry/blob/master/tests/polygon2d_test.py
As long as you add a function that starts with the word 'test_', your function will be included in the pytest run. You can see the other tests there if you need an example to follow.

I also wanted to add another side note to this issue that, if in the process of creating the boolean union, you realize that there's a similar way to get the boolean intersection between the two polygons, that would be very helpful to know.

**Comment by Derek52** [comment]
Hi,
I will return an array then, I like that approach.

And I tried adding a method to that test file, and it didn't work. And I just figured out it is because I installed ladybug-geometry on my system through Pip. I uninstalled that, so I only have the local source files for ladybug, but when I run the tests, I get an error saying the tests can't find a module named ladybug_geometry. Are you able to tell me what i'm doing wrong? It seems like the tests should just work. But they can't seem to find the ladybug source folder.

**Comment by chriswmackey** [comment]
@Derek52 ,

You can run the tests locally from command line by using the following steps:
1. Install pytest by typing `pip install pytest`
2. Navigate your command window to the root of the reop on your local machine.
3. Type `pytest .\tests`

Then you should see all the tests will run and you'll get info about all of the errors. 

The tests will also run automatically when you send the PR so we'll have another chance to catch things there. This automated run of the tests when you send the PR will also verify that the test runs correctly in both Python 2.7 and 3.7.

**Comment by chriswmackey** [comment]
I have to apologize as I just realized that we were missing an `__init__.py` in the tests folder. This would have prevented the tests from running correctly if you were running Python 2 and I just included a fix in this change here: https://github.com/ladybug-tools/ladybug-geometry/pull/63

So it's possible that this was the issue you were experiencing.

**Comment by chriswmackey** [comment]
This has been addressed!

https://github.com/ladybug-tools/ladybug-geometry/pull/366
