### ISSUE TITLE
Implement a better way to turn surfaces with holes into singular surfaces

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-geometry#7]
Looking through the [honeybee-grasshopper plus library](https://github.com/ladybug-tools/honeybee-grasshopper/blob/master/honeybee/plus.py), I can see that, any time a polygon is encountered with a hole in it, it is simply meshed into a bunch of triangles even though it is planar.  I always felt that this introduced a lot of unnecessary messiness into models since there is a relatively easy way to convert a shape like this into a single polygon by connecting each hole to the closest hole or the edge of the shape.

Take for example this shape:
![image](https://user-images.githubusercontent.com/5567574/55337208-3857f380-546c-11e9-821e-115c55553578.png)

It can be converted into a single polygon like so:
![image](https://user-images.githubusercontent.com/5567574/55337284-59b8df80-546c-11e9-9357-8809b15a778a.png)

I think something like this could be easily implemented as a classmethod on the `Surface3D`.  It would be a method like `from_boundary_and_holes` and you can pass it separate vertices for the boundary of the shape and the holes within the shape.  It will search for the closest hole to the boundary and draw a line between this hole and the edge. Then it will take the next closest hole, figure out if it is closer to the edge of the whole shape or the first hole and then draw a line to the closest one, etc.

With something like this, I think we could keep many models a lot cleaner and with fewer surfaces.  It can also mean that straight skeleton methods are still meaningful for the surface, like when one would like to do core/perimeter zoning for a floor plate with a courtyard.  Lastly, it means that we only need to resort to meshing when a curved surface is encountered, which means that 90% of energy models will be free from such triangulated patterns.

**Comment by theo-armour** [comment]
@chriswmackey 

The surface with holes defined topologically using a continuous polyline outline method is in use in RAD files. This format has been in user for decades and therefore must be considered a successful method. I came across this method when building my [Spider RAD Viewer]( https://www.ladybug.tools/spider-rad-viewer/rad-viewer).

Issues we encountered included:
* Not easy to identify if a line segment is a surface edge, a surface hole or a surface connector
* Dealing with the 'connector' lines when there is a grid of openings or a group of oddly shaped openings can become very tricky
* Drawing a surface with a hole with a surface with a hole might make connector lines visible
* In some models the opening are drawn in the same clockwise/counterclockwise direction as the exterior surface in other models they are in the reverse direction. If I remember correctly, some models have openings going in both directions. This can be dealt with bust takes much code for the checking

Regarding the triangular face method, I do agree that it create a s**tload or triangles. On the other I note that method of using separate perimeter vertices and hole/opening vertices is used by apps I am quite familiar with: gbXML and Three.js.

Using this method has some benefits
* Ascertaining areas 
* Drawing parallel offsets 
* Using multiple edge/line styles
* Show/hide the different elements
* Assigning attributes such as materials
* etc

BTW, the triangles are generally only created a render-time. So they should have no impact on file size or data complexity (unless you have a need I do not know about). The triangles are necessary only because they keep the GPU happy.

I hope this helps. Feel free to continue the discussion

**Comment by chriswmackey** [comment]
@theo-armour ,

Thanks for the comments here.  I have implemented the continuous outline method and I have it working so that it still keeps track of what is a hole and what is the outer boundary:
https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry3d/face.py#L202

Thanks again and I think that this will work well.

**Comment by theo-armour** [comment]
@chriswmackey 

I see that you are keeping separate lists of boundary vertices and hole vertices. I think this is a good idea. It should keep the gbXML peeps happy. And the continuous boundary should keep the radiance peeps happy. Fingers crossed it all works out.
